/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sqs;

import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.AmazonSQSClientBuilder;
import com.amazonaws.services.sqs.model.*;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class App {

    public static void main(String[] args) {
        final AmazonSQS sqs = AmazonSQSClientBuilder.defaultClient();
        final String queueName = sqs.getQueueUrl(args[1]).getQueueUrl();

        switch(args[0]) {
            case("send"):
                sendQueue(sqs, queueName, args[2]);
                break;
            case ("receive"):
                receiveQueue(sqs, queueName);
        }
    }

    private static int sendQueue(AmazonSQS sqs, String queueName, String message) {
        SendMessageRequest sendMessage = new SendMessageRequest()
                .withQueueUrl(queueName)
                .withMessageBody(message)
                .withDelaySeconds(5);
        int statusCode = sqs.sendMessage(sendMessage).getSdkHttpMetadata().getHttpStatusCode();
        System.out.println(statusCode);
        return statusCode;
    }

    private static void receiveQueue(AmazonSQS sqs, String queueName) {
        List<Message> messages = sqs.receiveMessage(queueName).getMessages();
        List<String> messageBody = new ArrayList<>();
        messages.forEach(message -> messageBody.add(message.getBody()));
        System.out.println(Arrays.toString(messageBody.toArray()));
        for (Message message : messages) {
            sqs.deleteMessage(queueName, message.getReceiptHandle());
        }
    }
}
